import { BRAMLEY_CLAIM_IDS, BRAMLEY_GAP_IDS, BRAMLEY_INPUT_IDS, BRAMLEY_OBSERVATION_IDS, BRAMLEY_SOURCE_IDS } from "./ids";
import { directToComms } from "./incoming-helpers";

/** When comms first became actively engaged (duty manager handover). */
const COMMS_ENGAGED = "2026-05-11T05:42:00";

export const bramleyIncomingUpdates = [
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.dutyManagerCommsBrief,
      inputType: "DUTY SUMMARY",
      title: "Duty manager summary to comms",
      senderTeam: "Duty Station Manager",
      channel: "phone briefing to corporate affairs duty",
      summary:
        "Handback delay at main entrance after overnight works. Station open via side entrance; trains running. Comms asked to open Metis issue and help with passenger/social lines.",
      fullText: [
        "Duty manager → corporate affairs duty phone briefing",
        "",
        "Situation: planned overnight works largely complete but main entrance remains closed pending ceiling panel sign-off.",
        "Station is operating via side entrance with extra staff/security being deployed.",
        "NOC confirms trains calling — no service change.",
        "Customer team reports growing confusion at main doors; no major crowding yet.",
        "No confirmed safety failure; facilities inspection still required before main entrance reopening.",
        "",
        "Reported overnight sequence (described in this briefing, not live comms channels):",
        "- Sun 20:00 — planned works notice issued for concourse lighting, gates and wayfinding; 05:30 handback target.",
        "- Sun 21:15 — contractor mobilised on site.",
        "- Mon 04:28 — contractor handback note: ceiling panel sign-off pending near main entrance (possible roof drain residue; not confirmed active leak).",
        "- Mon 04:35 — station manager: main entrance unlikely at 05:30; side entrance proposed with extra staffing from 05:45.",
        "- Mon 04:50 — security: barriers and two additional officers available from 05:45.",
        "- Mon 04:55 — NOC: trains continue to call; no service change.",
        "- Mon 05:32 — customer service: passengers asking at help point; low crowding at side entrance.",
        "",
        "Ask of comms:",
        "- Open controlled issue record in Metis and log the duty overnight pack as source-backed records.",
        "- Prepare staff and passenger lines distinguishing main entrance closure vs whole-station closure.",
        "- Stand by for possible social/media attention during the morning peak.",
      ].join("\n"),
      suggestedTimelineLabel: "Comms engaged",
      becomesSource: false,
      linkedSourceId: null,
      issueRecordImpacts: { statusNote: "Active issue opened — comms engaged" },
    },
    { eventOccurredAt: COMMS_ENGAGED, addedToMetisAt: COMMS_ENGAGED },
  ),
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.overnightPackLogged,
      inputType: "COMMS INTAKE",
      title: "Duty overnight pack logged in Metis",
      senderTeam: "Corporate Affairs",
      channel: "Metis intake from duty handover",
      summary:
        "Corporate Affairs logs source-backed records from the duty manager overnight pack: planned works, contractor handback, station/security/NOC updates and customer floor report.",
      fullText: [
        "Corporate Affairs — duty overnight pack logged",
        "",
        "Logged from duty manager phone briefing at 05:42. Transcribed items from the overnight sequence:",
        "",
        "Planned works notice (reported Sun 20:00)",
        "Overnight concourse lighting, ticket gate and wayfinding; 05:30 handback target; no planned train disruption.",
        "",
        "Contractor mobilisation (reported Sun 21:15)",
        "Team on site; works commenced.",
        "",
        "Contractor handback note (reported Mon 04:28)",
        "The contractor has held back sign-off on the ceiling panels near the main entrance after noting staining or residue that may relate to a roof drain. This has not been confirmed as an active leak or structural issue.",
        "",
        "Station manager escalation (reported Mon 04:35)",
        "Main entrance unlikely at 05:30; side entrance proposed with extra staffing from 05:45 if security confirms.",
        "",
        "Security update (reported Mon 04:50)",
        "Additional officers and barriers available from 05:45.",
        "",
        "NOC confirmation (reported Mon 04:55)",
        "Trains continue to call; no service change.",
        "",
        "Customer service floor report (reported Mon 05:32)",
        "Passengers confused at main doors; low crowding at the side entrance.",
      ].join("\n"),
      suggestedTimelineLabel: "Overnight pack logged",
      becomesSource: false,
      linkedSourceId: null,
      issueRecordImpacts: {
        claimsAdded: [
          BRAMLEY_CLAIM_IDS.c1,
          BRAMLEY_CLAIM_IDS.c2,
          BRAMLEY_CLAIM_IDS.c3,
          BRAMLEY_CLAIM_IDS.c4,
          BRAMLEY_CLAIM_IDS.c5,
          BRAMLEY_CLAIM_IDS.c6,
        ],
        gapsOpened: [
          BRAMLEY_GAP_IDS.ceilingSafe,
          BRAMLEY_GAP_IDS.reopeningTime,
          BRAMLEY_GAP_IDS.sideEntranceFlow,
          BRAMLEY_GAP_IDS.publicLineShut,
        ],
        gapsClosed: [BRAMLEY_GAP_IDS.trainServices],
        observationsAdded: [
          BRAMLEY_OBSERVATION_IDS.o1,
          BRAMLEY_OBSERVATION_IDS.o3,
          BRAMLEY_OBSERVATION_IDS.o4,
        ],
      },
    },
    {
      eventOccurredAt: "2026-05-11T05:50:00",
      receivedByCommsAt: COMMS_ENGAGED,
      addedToMetisAt: "2026-05-11T05:50:00",
    },
  ),
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.socialSignal,
      inputType: "SOCIAL SIGNAL",
      title: "Social monitoring — local posts say station is shut",
      senderTeam: "Comms Monitoring",
      channel: "social monitoring note",
      summary:
        "Three local posts describe the station as shut, which is inaccurate because side entrance is open and trains are running.",
      fullText: [
        "Social monitoring note (paraphrased, fictional)",
        "",
        "Approx. 03 local posts in 40 minutes describe Bramley Junction as 'shut' or 'closed'.",
        "Example themes: 'can't get in', 'station closed again', 'no trains' (last is inaccurate).",
        "No verified influencer amplification. Engagement modest.",
        "Recommended: short corrective line emphasising trains running and side entrance open.",
      ].join("\n"),
      suggestedTimelineLabel: "Social inaccuracy",
      becomesSource: true,
      linkedSourceId: BRAMLEY_SOURCE_IDS.socialSignal,
      issueRecordImpacts: {
        claimsAdded: [BRAMLEY_CLAIM_IDS.c7],
        observationsAdded: [BRAMLEY_OBSERVATION_IDS.o2],
        statusNote: "Managed operational disruption",
      },
    },
    { eventOccurredAt: "2026-05-11T05:48:00", addedToMetisAt: "2026-05-11T05:49:00" },
  ),
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.pressCall,
      inputType: "PRESS CALL",
      title: "Press office call log — reporter asks about reopening",
      senderTeam: "Press Office",
      channel: "call log",
      summary: "Local reporter asks whether planned works overran and whether passengers were locked out.",
      fullText: [
        "Press call log — fictional local outlet",
        "",
        "Reporter questions:",
        "1) Did planned overnight works overrun?",
        "2) Were passengers unable to enter the station?",
        "3) When will the main entrance reopen?",
        "",
        "Deadline: requested response within 45 minutes for online update.",
        "No broadcast crew on site reported.",
      ].join("\n"),
      suggestedTimelineLabel: "Press enquiry",
      becomesSource: true,
      linkedSourceId: BRAMLEY_SOURCE_IDS.pressCall,
      issueRecordImpacts: {},
    },
    { eventOccurredAt: "2026-05-11T06:08:00", addedToMetisAt: "2026-05-11T06:09:00" },
  ),
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.execPositionRequest,
      inputType: "EXEC REQUEST",
      title: "Executive office request for short position note",
      senderTeam: "Executive Office",
      channel: "email to corporate affairs duty",
      summary:
        "Regional director's office requests a short position note for morning leadership covering customer impact, media handling and expected reopening.",
      fullText: [
        "Executive office request — position note",
        "",
        "Please provide a short executive position note covering:",
        "- what happened overnight and this morning at Bramley Junction",
        "- customer impact and mitigations",
        "- media/social handling and open risks",
        "- expected main entrance reopening (if known)",
        "",
        "Audience: regional leadership morning call.",
        "Length: one page maximum.",
        "Deadline: before 07:00 where possible.",
      ].join("\n"),
      suggestedTimelineLabel: "Executive request",
      becomesSource: false,
      linkedSourceId: null,
      issueRecordImpacts: {},
    },
    { eventOccurredAt: "2026-05-11T06:35:00", addedToMetisAt: "2026-05-11T06:36:00" },
  ),
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.stationUpdateFlow,
      inputType: "STATION UPDATE",
      title: "Station manager update — passenger flow manageable",
      senderTeam: "Station Manager",
      channel: "phone update to corporate affairs",
      summary: "Side entrance open, extra staff deployed, passenger flow manageable, no safety concerns reported.",
      fullText: [
        "Station manager phone update to corporate affairs",
        "",
        "Reported event time: 06:22 (station ops update).",
        "Received by comms: 06:20 following press enquiry coordination.",
        "",
        "Side entrance open with additional staff and security.",
        "Queue time under 3 minutes at time of report.",
        "Main entrance remains closed pending facilities clearance.",
        "No safety incidents. Customer team reports improving clarity with written line.",
      ].join("\n"),
      suggestedTimelineLabel: "Flow manageable",
      becomesSource: true,
      linkedSourceId: BRAMLEY_SOURCE_IDS.stationUpdateFlow,
      issueRecordImpacts: { gapsClosed: [BRAMLEY_GAP_IDS.sideEntranceFlow] },
    },
    {
      eventOccurredAt: "2026-05-11T06:22:00",
      receivedByCommsAt: "2026-05-11T06:20:00",
      addedToMetisAt: "2026-05-11T06:24:00",
    },
  ),
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.facilitiesNote,
      inputType: "FACILITIES NOTE",
      title: "Facilities inspection summary forwarded to comms",
      senderTeam: "Facilities Engineer",
      channel: "email to station manager, copied to comms",
      summary:
        "Ceiling panels secure. Small roof drain repair needed later. Main entrance can reopen after clean-up and signage check.",
      fullText: [
        "Facilities inspection note — main entrance canopy",
        "",
        "Reported event time: inspection completed ~07:05.",
        "Forwarded to comms: 07:06 via station manager email.",
        "",
        "Ceiling panels secure for passenger use.",
        "Minor staining consistent with historic drain seepage; no active water ingress observed.",
        "Remedial roof drain repair scheduled non-urgent within 14 days.",
        "Clearance: main entrance may reopen after contractor clean-up and signage check.",
      ].join("\n"),
      suggestedTimelineLabel: "Ceiling cleared",
      becomesSource: true,
      linkedSourceId: BRAMLEY_SOURCE_IDS.facilitiesNote,
      issueRecordImpacts: {
        claimsAdded: [BRAMLEY_CLAIM_IDS.c8],
        gapsClosed: [BRAMLEY_GAP_IDS.ceilingSafe],
        statusNote: "Reopening expected shortly",
      },
    },
    {
      eventOccurredAt: "2026-05-11T07:05:00",
      sourceTimestamp: "2026-05-11T07:00:00",
      receivedByCommsAt: "2026-05-11T07:06:00",
      addedToMetisAt: "2026-05-11T07:08:00",
    },
  ),
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.accessibilityNote,
      inputType: "ACCESSIBILITY NOTE",
      title: "Accessibility assessment forwarded to comms",
      senderTeam: "Accessibility Lead",
      channel: "email to corporate affairs",
      summary: "Step-free access available through side entrance, but temporary signage needs improvement.",
      fullText: [
        "Accessibility assessment",
        "",
        "Reported event time: 07:50 observation window.",
        "Received by comms: 07:52.",
        "",
        "Step-free route available via side entrance lift (operational).",
        "Temporary signage not meeting usual contrast/position standards.",
        "Recommendation: deploy high-visibility directional totems within 30 minutes.",
        "No reported barriers for wheelchair users during observation window.",
      ].join("\n"),
      suggestedTimelineLabel: "Accessibility check",
      becomesSource: true,
      linkedSourceId: BRAMLEY_SOURCE_IDS.accessibilityNote,
      issueRecordImpacts: {
        gapsOpened: [BRAMLEY_GAP_IDS.accessibility],
        observationsAdded: [BRAMLEY_OBSERVATION_IDS.o5],
      },
    },
    {
      eventOccurredAt: "2026-05-11T07:50:00",
      receivedByCommsAt: "2026-05-11T07:52:00",
      addedToMetisAt: "2026-05-11T07:54:00",
    },
  ),
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.opsConfirmation,
      inputType: "OPS CONFIRMATION",
      title: "Station manager confirmation — main entrance reopened",
      senderTeam: "Station Manager",
      channel: "phone confirmation to corporate affairs",
      summary: "Main entrance reopened. Side entrance remains available. Staff continue to monitor.",
      fullText: [
        "Reopening confirmation — station manager to comms",
        "",
        "Reported event time: main entrance opened 08:12.",
        "Received by comms: 08:13 phone confirmation.",
        "",
        "Main entrance opened after clean-up and signage checks.",
        "Side entrance remains open to avoid bottlenecks.",
        "Passenger flow normalising. No further press queries in last 20 minutes.",
      ].join("\n"),
      suggestedTimelineLabel: "Main entrance open",
      becomesSource: true,
      linkedSourceId: BRAMLEY_SOURCE_IDS.opsConfirmation,
      issueRecordImpacts: {
        claimsAdded: [BRAMLEY_CLAIM_IDS.c9],
        gapsClosed: [BRAMLEY_GAP_IDS.reopeningTime, BRAMLEY_GAP_IDS.publicLineShut],
        statusNote: "Operational disruption closed",
      },
    },
    {
      eventOccurredAt: "2026-05-11T08:12:00",
      receivedByCommsAt: "2026-05-11T08:13:00",
      addedToMetisAt: "2026-05-11T08:15:00",
    },
  ),
  directToComms(
    {
      id: BRAMLEY_INPUT_IDS.execAction,
      inputType: "EXEC ACTION",
      title: "Follow-up actions requested",
      senderTeam: "Regional Operations Director",
      channel: "exec action note",
      summary:
        "Request short review of what happened, customer impact, media handling, and improvements for future planned works.",
      fullText: [
        "Executive follow-up request",
        "",
        "Please provide a short post-incident review covering:",
        "- timeline of handback and comms decisions",
        "- customer impact assessment",
        "- media/social handling",
        "- lessons for future planned works handback criteria",
        "",
        "Target: draft to regional leadership within 2 working days.",
      ].join("\n"),
      suggestedTimelineLabel: "Exec follow-up",
      becomesSource: false,
      linkedSourceId: null,
      issueRecordImpacts: {
        gapsOpened: [BRAMLEY_GAP_IDS.followUpWorks],
        observationsAdded: [BRAMLEY_OBSERVATION_IDS.o6],
        statusNote: "Review / audit stage",
      },
    },
    { eventOccurredAt: "2026-05-11T08:40:00", addedToMetisAt: "2026-05-11T08:41:00" },
  ),
];
