import {
  BRAMLEY_CLAIM_IDS,
  BRAMLEY_GAP_IDS,
  BRAMLEY_INPUT_IDS,
  BRAMLEY_OBSERVATION_IDS,
  BRAMLEY_SOURCE_IDS,
} from "./ids";
import type {
  BramleyClaimExport,
  BramleyObservationExport,
  BramleyOpenQuestionExport,
  BramleySourceExport,
} from "./types";
import { bramleyIncomingUpdates } from "./incoming-inputs";
import { bramleyIso } from "./timestamps";

function inputById(id: string) {
  const row = bramleyIncomingUpdates.find((u) => u.id === id);
  if (!row) throw new Error(`Missing Bramley input ${id}`);
  return row;
}

function metisAddedAt(inputId: string): string {
  return inputById(inputId).addedToMetisAt;
}

const bramleySourcesBase = [
  {
    id: BRAMLEY_SOURCE_IDS.opsPlan,
    sourceCode: "SRC-001",
    title: "Planned works notice — Bramley Junction overnight",
    tier: "Authoritative internal record",
    reliability: "High (internal planned works notice)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.overnightPackLogged}`,
    snippet: "Overnight concourse lighting, ticket gate and wayfinding works. Expected handback 05:30. No planned train service disruption.",
    timestampLabel: "Sun 20:00",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.overnightPackLogged,
  },
  {
    id: BRAMLEY_SOURCE_IDS.worksUpdate,
    sourceCode: "SRC-002",
    title: "Contractor mobilisation update",
    tier: "Internal operational source",
    reliability: "High (contractor site report)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.overnightPackLogged}`,
    snippet: "Team on site; works commenced on lighting, gates and signage. Handback target 05:30.",
    timestampLabel: "Sun 21:15",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.overnightPackLogged,
  },
  {
    id: BRAMLEY_SOURCE_IDS.contractorNote,
    sourceCode: "SRC-003",
    title: "Handback note — ceiling panels pending sign-off",
    tier: "Internal operational source",
    reliability: "Medium–High (contractor; pending engineering confirmation)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.overnightPackLogged}`,
    snippet: "Final sign-off withheld on main entrance ceiling zone; possible roof drain seepage — not confirmed as active leak.",
    timestampLabel: "Mon 04:28",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.overnightPackLogged,
  },
  {
    id: BRAMLEY_SOURCE_IDS.stationManagerEarly,
    sourceCode: "SRC-004",
    title: "Station manager escalation — main entrance delay",
    tier: "Internal operational source",
    reliability: "High (station manager operational report)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.overnightPackLogged}`,
    snippet: "Main entrance unlikely at 05:30; side entrance proposed with extra staffing from 05:45.",
    timestampLabel: "Mon 04:35",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.overnightPackLogged,
  },
  {
    id: BRAMLEY_SOURCE_IDS.securityUpdate,
    sourceCode: "SRC-005",
    title: "Security update — side entrance capacity",
    tier: "Internal operational source",
    reliability: "High (security supervisor)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.overnightPackLogged}`,
    snippet: "Additional officers and barriers available from 05:45.",
    timestampLabel: "Mon 04:50",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.overnightPackLogged,
  },
  {
    id: BRAMLEY_SOURCE_IDS.networkOps,
    sourceCode: "SRC-006",
    title: "Network Operations — trains calling",
    tier: "Authoritative internal record",
    reliability: "High (NOC confirmation)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.overnightPackLogged}`,
    snippet: "No train service changes; station access routing is a station matter.",
    timestampLabel: "Mon 04:55",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.overnightPackLogged,
  },
  {
    id: BRAMLEY_SOURCE_IDS.customerTeam,
    sourceCode: "SRC-007",
    title: "Customer service floor report",
    tier: "Internal operational source",
    reliability: "Medium (operational observation)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.overnightPackLogged}`,
    snippet: "Passengers confused by closed main doors; low crowding; request approved written line.",
    timestampLabel: "Mon 05:32",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.overnightPackLogged,
  },
  {
    id: BRAMLEY_SOURCE_IDS.socialSignal,
    sourceCode: "SRC-008",
    title: "Social monitoring — inaccurate closure posts",
    tier: "Social monitoring",
    reliability: "Medium (monitoring summary; paraphrased)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.socialSignal}`,
    snippet: "Local posts describe station as shut; side entrance open and trains running.",
    timestampLabel: "Mon 05:48",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.socialSignal,
  },
  {
    id: BRAMLEY_SOURCE_IDS.pressCall,
    sourceCode: "SRC-009",
    title: "Press call log — local reporter",
    tier: "Media enquiry",
    reliability: "High (press office log)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.pressCall}`,
    snippet: "Questions on overrun, passenger access, and reopening time; 45-minute response window.",
    timestampLabel: "Mon 06:08",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.pressCall,
  },
  {
    id: BRAMLEY_SOURCE_IDS.stationUpdateFlow,
    sourceCode: "SRC-010",
    title: "Station update — passenger flow",
    tier: "Internal operational source",
    reliability: "High (station manager)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.stationUpdateFlow}`,
    snippet: "Side entrance open; queues under 3 minutes; main entrance still closed.",
    timestampLabel: "Mon 06:22",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.stationUpdateFlow,
  },
  {
    id: BRAMLEY_SOURCE_IDS.facilitiesNote,
    sourceCode: "SRC-011",
    title: "Facilities inspection — ceiling secure",
    tier: "Internal operational source",
    reliability: "High (facilities engineer inspection)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.facilitiesNote}`,
    snippet: "Panels secure; minor drain remedial works later; clearance to reopen after clean-up.",
    timestampLabel: "Mon 07:05",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.facilitiesNote,
  },
  {
    id: BRAMLEY_SOURCE_IDS.accessibilityNote,
    sourceCode: "SRC-012",
    title: "Accessibility assessment — side entrance",
    tier: "Internal operational source",
    reliability: "Medium–High (accessibility lead)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.accessibilityNote}`,
    snippet: "Step-free route via side lift; temporary signage needs improvement.",
    timestampLabel: "Mon 07:50",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.accessibilityNote,
  },
  {
    id: BRAMLEY_SOURCE_IDS.opsConfirmation,
    sourceCode: "SRC-013",
    title: "Reopening confirmation — main entrance",
    tier: "Internal operational source",
    reliability: "High (station manager)",
    note: `Linked incoming update ${BRAMLEY_INPUT_IDS.opsConfirmation}`,
    snippet: "Main entrance opened 08:12; side entrance remains available.",
    timestampLabel: "Mon 08:12",
    linkedIncomingUpdateId: BRAMLEY_INPUT_IDS.opsConfirmation,
  },
] as const;

export const bramleySources: BramleySourceExport[] = bramleySourcesBase.map((s) => {
  const input = inputById(s.linkedIncomingUpdateId);
  return {
    ...s,
    eventOccurredAt: input.eventOccurredAt,
    addedToMetisAt: input.addedToMetisAt,
  };
});

export const bramleyClaims: BramleyClaimExport[] = [
  {
    id: BRAMLEY_CLAIM_IDS.c1,
    claimCode: "CLM-001",
    text: "Planned overnight works were scheduled at Bramley Junction with expected handback before the morning peak.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [BRAMLEY_SOURCE_IDS.opsPlan],
    linkedIncomingUpdateIds: [BRAMLEY_INPUT_IDS.overnightPackLogged],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
  },
  {
    id: BRAMLEY_CLAIM_IDS.c2,
    claimCode: "CLM-002",
    text: "Most planned works were completed as expected overnight.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [BRAMLEY_SOURCE_IDS.worksUpdate, BRAMLEY_SOURCE_IDS.contractorNote],
    linkedIncomingUpdateIds: [BRAMLEY_INPUT_IDS.overnightPackLogged, BRAMLEY_INPUT_IDS.overnightPackLogged],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
  },
  {
    id: BRAMLEY_CLAIM_IDS.c3,
    claimCode: "CLM-003",
    text: "Main entrance opening was delayed pending final inspection of ceiling panels near the main entrance.",
    status: "Confirmed",
    notes: "Pending sign-off was precautionary; not reported as confirmed structural failure.",
    linkedSourceIds: [BRAMLEY_SOURCE_IDS.contractorNote, BRAMLEY_SOURCE_IDS.stationManagerEarly],
    linkedIncomingUpdateIds: [BRAMLEY_INPUT_IDS.overnightPackLogged, BRAMLEY_INPUT_IDS.overnightPackLogged],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
  },
  {
    id: BRAMLEY_CLAIM_IDS.c4,
    claimCode: "CLM-004",
    text: "The station remained open via the side entrance while the main entrance was unavailable.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [BRAMLEY_SOURCE_IDS.stationManagerEarly, BRAMLEY_SOURCE_IDS.stationUpdateFlow],
    linkedIncomingUpdateIds: [BRAMLEY_INPUT_IDS.overnightPackLogged, BRAMLEY_INPUT_IDS.stationUpdateFlow],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.stationUpdateFlow),
  },
  {
    id: BRAMLEY_CLAIM_IDS.c5,
    claimCode: "CLM-005",
    text: "Train services continued to call at Bramley Junction with no planned service changes.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [BRAMLEY_SOURCE_IDS.networkOps, BRAMLEY_SOURCE_IDS.opsPlan],
    linkedIncomingUpdateIds: [BRAMLEY_INPUT_IDS.overnightPackLogged],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
  },
  {
    id: BRAMLEY_CLAIM_IDS.c6,
    claimCode: "CLM-006",
    text: "Passenger impact was limited but visible at the main entrance during the early morning peak.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [BRAMLEY_SOURCE_IDS.customerTeam, BRAMLEY_SOURCE_IDS.stationUpdateFlow],
    linkedIncomingUpdateIds: [BRAMLEY_INPUT_IDS.overnightPackLogged, BRAMLEY_INPUT_IDS.stationUpdateFlow],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.stationUpdateFlow),
  },
  {
    id: BRAMLEY_CLAIM_IDS.c7,
    claimCode: "CLM-007",
    text: "Some external commentary incorrectly described the station as fully shut.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [BRAMLEY_SOURCE_IDS.socialSignal],
    linkedIncomingUpdateIds: [BRAMLEY_INPUT_IDS.socialSignal],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.socialSignal),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.socialSignal),
  },
  {
    id: BRAMLEY_CLAIM_IDS.c8,
    claimCode: "CLM-008",
    text: "Ceiling panels in the main entrance area were later confirmed secure for passenger use.",
    status: "Confirmed",
    notes: "Remedial roof drain work scheduled non-urgent.",
    linkedSourceIds: [BRAMLEY_SOURCE_IDS.facilitiesNote],
    linkedIncomingUpdateIds: [BRAMLEY_INPUT_IDS.facilitiesNote],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.facilitiesNote),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.facilitiesNote),
  },
  {
    id: BRAMLEY_CLAIM_IDS.c9,
    claimCode: "CLM-009",
    text: "The main entrance reopened at 08:12 following clean-up and signage checks.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [BRAMLEY_SOURCE_IDS.opsConfirmation],
    linkedIncomingUpdateIds: [BRAMLEY_INPUT_IDS.opsConfirmation],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.opsConfirmation),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.opsConfirmation),
  },
];

export const bramleyOpenQuestions: BramleyOpenQuestionExport[] = [
  {
    id: BRAMLEY_GAP_IDS.ceilingSafe,
    gapCode: "Q-001",
    title: "Is the ceiling area safe for passenger use?",
    prompt: "Has facilities/engineering confirmed the main entrance ceiling zone is safe to open?",
    whyItMatters: "Reopening the main entrance without confirmation could create safety and reputational risk.",
    stakeholder: "Station operations / Facilities",
    severity: "Critical",
    status: "Resolved",
    partiallyAnsweredAt: null,
    resolvedAt: bramleyIso("2026-05-11T07:05:00"),
    resolvedByIncomingUpdateId: BRAMLEY_INPUT_IDS.facilitiesNote,
    resolutionNote: null,
    linkedClaimIds: [BRAMLEY_CLAIM_IDS.c3, BRAMLEY_CLAIM_IDS.c8],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.facilitiesNote),
  },
  {
    id: BRAMLEY_GAP_IDS.sideEntranceFlow,
    gapCode: "Q-002",
    title: "Can the side entrance safely handle early morning passenger flow?",
    prompt: "Is side entrance staffing, barriers and wayfinding sufficient for the peak?",
    whyItMatters: "Passenger safety and queue management depend on a viable alternate route.",
    stakeholder: "Station manager / Security",
    severity: "Important",
    status: "Resolved",
    partiallyAnsweredAt: null,
    resolvedAt: bramleyIso("2026-05-11T06:30:00"),
    resolvedByIncomingUpdateId: BRAMLEY_INPUT_IDS.stationUpdateFlow,
    resolutionNote: null,
    linkedClaimIds: [BRAMLEY_CLAIM_IDS.c4],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.stationUpdateFlow),
  },
  {
    id: BRAMLEY_GAP_IDS.trainServices,
    gapCode: "Q-003",
    title: "Are train services affected?",
    prompt: "Is any train service change required or planned?",
    whyItMatters: "Public lines must distinguish station access from train service.",
    stakeholder: "Network Operations",
    severity: "Important",
    status: "Resolved",
    partiallyAnsweredAt: null,
    resolvedAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    resolvedByIncomingUpdateId: BRAMLEY_INPUT_IDS.overnightPackLogged,
    resolutionNote: "NOC confirmation recorded from duty overnight pack (operational report ~04:55).",
    linkedClaimIds: [BRAMLEY_CLAIM_IDS.c5],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
  },
  {
    id: BRAMLEY_GAP_IDS.publicLineShut,
    gapCode: "Q-004",
    title: "What public line should be used if asked whether the station is shut?",
    prompt: "What wording distinguishes main entrance closure from whole-station closure?",
    whyItMatters: "Social posts and passenger confusion create reputational risk.",
    stakeholder: "Corporate Affairs",
    severity: "Important",
    status: "Resolved",
    partiallyAnsweredAt: null,
    resolvedAt: bramleyIso("2026-05-11T06:18:00"),
    resolvedByIncomingUpdateId: BRAMLEY_INPUT_IDS.pressCall,
    resolutionNote:
      "Approved passenger, social and holding press lines in use from 05:52–06:18 — distinguishes main entrance closure from whole-station closure.",
    linkedClaimIds: [BRAMLEY_CLAIM_IDS.c7],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.pressCall),
  },
  {
    id: BRAMLEY_GAP_IDS.reopeningTime,
    gapCode: "Q-005",
    title: "What is the expected main entrance reopening time?",
    prompt: "When can we commit to reopening the main entrance?",
    whyItMatters: "Press and passenger messaging need a realistic time window.",
    stakeholder: "Station operations",
    severity: "Important",
    status: "Resolved",
    partiallyAnsweredAt: bramleyIso("2026-05-11T07:22:00"),
    resolvedAt: bramleyIso("2026-05-11T08:12:00"),
    resolvedByIncomingUpdateId: BRAMLEY_INPUT_IDS.opsConfirmation,
    resolutionNote:
      "Working estimate ~08:00 in updated passenger message from 07:22; main entrance confirmed open 08:12.",
    linkedClaimIds: [BRAMLEY_CLAIM_IDS.c3],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.opsConfirmation),
  },
  {
    id: BRAMLEY_GAP_IDS.accessibility,
    gapCode: "Q-006",
    title: "Are accessibility arrangements adequate while the main entrance is closed?",
    prompt: "Is step-free access clearly signed and operationally supported?",
    whyItMatters: "Accessibility must be verified independently of general passenger flow.",
    stakeholder: "Accessibility lead",
    severity: "Important",
    status: "Open",
    partiallyAnsweredAt: null,
    resolvedAt: null,
    resolvedByIncomingUpdateId: null,
    resolutionNote:
      "Accessibility assessment logged in Metis; temporary signage improvements still being deployed (action required).",
    linkedClaimIds: [BRAMLEY_CLAIM_IDS.c4],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.accessibilityNote),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.accessibilityNote),
  },
  {
    id: BRAMLEY_GAP_IDS.followUpWorks,
    gapCode: "Q-007",
    title: "What follow-up action is needed before future planned works?",
    prompt: "What handback criteria, signage and pre-agreed passenger messaging should be updated?",
    whyItMatters: "Executive request for learning and prevention.",
    stakeholder: "Regional operations / Corporate Affairs",
    severity: "Watch",
    status: "Open",
    partiallyAnsweredAt: null,
    resolvedAt: null,
    resolvedByIncomingUpdateId: null,
    resolutionNote: null,
    linkedClaimIds: [],
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.execAction),
    updatedAt: metisAddedAt(BRAMLEY_INPUT_IDS.execAction),
  },
];

export const bramleyObservations: BramleyObservationExport[] = [
  {
    id: BRAMLEY_OBSERVATION_IDS.o1,
    observationCode: "OBS-001",
    title: "Main entrance vs whole station confusion",
    body: "The key communications risk is confusion between “main entrance closed” and “station closed”.",
    confidence: "Likely",
    authorRole: "Corporate Affairs",
    authorName: "Duty Comms Manager",
    timestampLabel: "Mon 04:40",
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
  },
  {
    id: BRAMLEY_OBSERVATION_IDS.o2,
    observationCode: "OBS-002",
    title: "Reputationally visible despite modest operational impact",
    body: "The issue is operationally modest but reputationally visible during the morning peak.",
    confidence: "Likely",
    authorRole: "Corporate Affairs",
    authorName: "Duty Comms Manager",
    timestampLabel: "Mon 05:50",
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.socialSignal),
  },
  {
    id: BRAMLEY_OBSERVATION_IDS.o3,
    observationCode: "OBS-003",
    title: "Avoid speculation on roof drainage",
    body: "Staff need a clear line to avoid speculation about roof drainage before facilities confirms.",
    confidence: "Confirmed",
    authorRole: "Station Operations",
    authorName: "Duty Station Support",
    timestampLabel: "Mon 04:36",
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
  },
  {
    id: BRAMLEY_OBSERVATION_IDS.o4,
    observationCode: "OBS-004",
    title: "Lead with what remains available",
    body: "Passenger messaging should lead with what remains available: trains running, side entrance open.",
    confidence: "Confirmed",
    authorRole: "Customer Experience",
    authorName: "Customer Service Lead",
    timestampLabel: "Mon 04:42",
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.overnightPackLogged),
  },
  {
    id: BRAMLEY_OBSERVATION_IDS.o5,
    observationCode: "OBS-005",
    title: "Check accessibility separately",
    body: "Accessibility impact should be checked separately, not assumed from general flow reports.",
    confidence: "Likely",
    authorRole: "Accessibility",
    authorName: "Accessibility Lead",
    timestampLabel: "Mon 07:52",
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.accessibilityNote),
  },
  {
    id: BRAMLEY_OBSERVATION_IDS.o6,
    observationCode: "OBS-006",
    title: "Future works handback focus",
    body: "Later review should focus on handback criteria, temporary signage and pre-agreed passenger messaging for planned works.",
    confidence: "Likely",
    authorRole: "Regional Operations",
    authorName: "Regional Operations Director",
    timestampLabel: "Mon 08:42",
    createdAt: metisAddedAt(BRAMLEY_INPUT_IDS.execAction),
  },
];
