import {
  NORTHBANK_BRIEF_VERSION_IDS,
  NORTHBANK_CIRCULATION_IDS,
  NORTHBANK_OUTPUT_IDS,
} from "./ids";
import type { NorthbankCirculationExport } from "./types";
import { northbankIso } from "./timestamps";

export const northbankCirculationEvents: NorthbankCirculationExport[] = [
  {
    id: NORTHBANK_CIRCULATION_IDS.execV1,
    at: northbankIso("2026-06-15T12:00:00"),
    eventType: "Circulated",
    channel: "Leadership distribution",
    audienceLabel: "Senior leadership",
    postureState: "Ready for review",
    note: "Executive brief V1 — pre-approval readiness position.",
    briefVersionId: NORTHBANK_BRIEF_VERSION_IDS.executiveV1,
    outputId: NORTHBANK_OUTPUT_IDS.executiveV1,
  },
  {
    id: NORTHBANK_CIRCULATION_IDS.pressHolding,
    at: northbankIso("2026-06-17T10:30:00"),
    eventType: "Shared for review",
    channel: "Press office",
    audienceLabel: "Trade media",
    postureState: "Ready for review",
    note: "Press holding variant after trade journalist enquiry.",
    briefVersionId: NORTHBANK_BRIEF_VERSION_IDS.executiveV1,
    outputId: NORTHBANK_OUTPUT_IDS.pressHolding,
  },
  {
    id: NORTHBANK_CIRCULATION_IDS.execV2,
    at: northbankIso("2026-06-18T12:30:00"),
    eventType: "Circulated",
    channel: "Leadership distribution",
    audienceLabel: "Senior leadership",
    postureState: "Approved",
    note: "Executive brief V2 — supersedes V1 after pricing and digital approvals.",
    briefVersionId: NORTHBANK_BRIEF_VERSION_IDS.executiveV2,
    outputId: NORTHBANK_OUTPUT_IDS.executiveV2,
  },
  {
    id: NORTHBANK_CIRCULATION_IDS.customerV2,
    at: northbankIso("2026-06-18T13:15:00"),
    eventType: "Published",
    channel: "Website / app",
    audienceLabel: "Customers",
    postureState: "Approved",
    note: "Customer message variant V2 with approved rate and channels.",
    briefVersionId: NORTHBANK_BRIEF_VERSION_IDS.executiveV2,
    outputId: NORTHBANK_OUTPUT_IDS.customerV2,
  },
  {
    id: NORTHBANK_CIRCULATION_IDS.exportPack,
    at: northbankIso("2026-06-19T11:05:00"),
    eventType: "Exported",
    channel: "Leadership pack",
    audienceLabel: "Senior leadership",
    postureState: "Approved",
    note: "HTML export of executive brief V2 for leadership circulation.",
    briefVersionId: NORTHBANK_BRIEF_VERSION_IDS.executiveV2,
    outputId: NORTHBANK_OUTPUT_IDS.exportedBrief,
  },
  {
    id: NORTHBANK_CIRCULATION_IDS.audit,
    at: northbankIso("2026-06-19T11:15:00"),
    eventType: "Audit recorded",
    channel: "Governance log",
    audienceLabel: "Governance record",
    postureState: "Approved",
    note: "Circulation audit for Green Saver launch readiness outputs.",
    briefVersionId: NORTHBANK_BRIEF_VERSION_IDS.executiveV2,
    outputId: NORTHBANK_OUTPUT_IDS.circulationAudit,
  },
];
