import {
  NORTHBANK_CLAIM_IDS,
  NORTHBANK_GAP_IDS,
  NORTHBANK_INPUT_IDS,
  NORTHBANK_OBSERVATION_IDS,
  NORTHBANK_SOURCE_IDS,
} from "./ids";
import { directToComms, fromProjectSource } from "./incoming-helpers";

export const northbankIncomingUpdates = [
  fromProjectSource(
    {
      id: NORTHBANK_INPUT_IDS.productScope,
      inputType: "PRODUCT UPDATE",
      title: "Product launch scope confirmed",
      senderTeam: "Savings Product Team",
      channel: "launch scope note",
      summary:
        "Product confirms target launch window, intended customer group and headline proposition for Green Saver.",
      fullText: [
        "Green Saver — launch scope note (fictional)",
        "",
        "Product: Green Saver — savings product linked to funding energy-efficient home improvements.",
        "Target launch window: week commencing 22 June 2026 (subject to dependencies).",
        "Intended customers: eligible existing and new savings customers meeting published criteria.",
        "Headline proposition: support greener homes through a dedicated savings rate — final wording subject to compliance/legal.",
        "",
        "[Metis note] Logged from product launch pack when Corporate Affairs opened the readiness issue.",
      ].join("\n"),
      suggestedTimelineLabel: "Launch scope",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.productScope,
      issueRecordImpacts: {
        claimsAdded: [NORTHBANK_CLAIM_IDS.c1, NORTHBANK_CLAIM_IDS.c2],
        observationsAdded: [NORTHBANK_OBSERVATION_IDS.o2],
      },
    },
    {
      eventOccurredAt: "2026-06-08T09:30:00",
      receivedByCommsAt: "2026-06-08T11:00:00",
      addedToMetisAt: "2026-06-08T11:00:00",
    },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.commsIntake,
      inputType: "COMMS INTAKE",
      title: "Corporate Affairs opens launch readiness issue",
      senderTeam: "Corporate Affairs",
      channel: "Metis issue setup",
      summary:
        "Comms creates the controlled launch readiness record to track confirmed claims, open questions and approved outputs.",
      fullText: [
        "Corporate Affairs — launch readiness issue opened",
        "",
        "Purpose: maintain a source-backed launch position for Green Saver across leadership, customer operations, digital and media.",
        "Discipline: separate confirmed claims from open questions; no external line without approved message variant.",
        "Dependencies tracked: pricing committee, compliance eligibility wording, legal environmental claims, app release, accessibility support.",
      ].join("\n"),
      suggestedTimelineLabel: "Issue opened",
      becomesSource: false,
      linkedSourceId: null,
      issueRecordImpacts: {
        statusNote: "Launch readiness issue opened in Metis",
        observationsAdded: [NORTHBANK_OBSERVATION_IDS.o3],
      },
    },
    { eventOccurredAt: "2026-06-08T11:00:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.pricingUpdate,
      inputType: "PRICING UPDATE",
      title: "Pricing recommendation submitted",
      senderTeam: "Commercial Pricing",
      channel: "pricing paper",
      summary: "Proposed launch rate and eligibility assumptions supplied; final pricing committee approval still pending.",
      fullText: [
        "Pricing recommendation — Green Saver (draft)",
        "",
        "Proposed launch rate: 4.25% gross/AER (fictional) for eligible balances within product limits.",
        "Assumptions: launch window as per product note; funding costs and competitor set as modelled 5 June.",
        "Status: recommendation only — pricing committee approval required before external use.",
        "Comms must not quote the rate externally until formal approval is recorded.",
      ].join("\n"),
      suggestedTimelineLabel: "Pricing proposed",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.pricingUpdate,
      issueRecordImpacts: {
        claimsAdded: [NORTHBANK_CLAIM_IDS.c3],
        gapsOpened: [NORTHBANK_GAP_IDS.pricingApproved],
        observationsAdded: [NORTHBANK_OBSERVATION_IDS.o1],
      },
    },
    { eventOccurredAt: "2026-06-09T10:15:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.complianceNote,
      inputType: "COMPLIANCE NOTE",
      title: "Compliance review flags eligibility wording",
      senderTeam: "Compliance",
      channel: "compliance review",
      summary: "Compliance asks comms not to describe the product as available to all customers until eligibility wording is final.",
      fullText: [
        "Compliance review — eligibility and fair value",
        "",
        "Do not state that Green Saver is available to all customers.",
        "Eligibility criteria and exclusions require approved wording before customer-facing or media use.",
        "Fair value summary to be attached to committee papers — not for external circulation.",
      ].join("\n"),
      suggestedTimelineLabel: "Eligibility flag",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.complianceNote,
      issueRecordImpacts: {
        claimsAdded: [NORTHBANK_CLAIM_IDS.c4],
        gapsOpened: [NORTHBANK_GAP_IDS.eligibilityWording],
      },
    },
    { eventOccurredAt: "2026-06-10T09:45:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.legalNote,
      inputType: "LEGAL NOTE",
      title: "Legal approves headline subject to caveat",
      senderTeam: "Legal",
      channel: "legal sign-off",
      summary: "Legal is comfortable with the broad launch narrative but wants careful wording around environmental claims.",
      fullText: [
        "Legal sign-off — Green Saver narrative (conditional)",
        "",
        "Broad launch narrative approved for internal readiness use.",
        "Environmental claims must avoid overclaiming — use 'support' / 'linked to' language, not guaranteed outcomes.",
        "Do not imply regulatory endorsement of green credentials.",
        "External materials remain subject to compliance-approved eligibility wording.",
      ].join("\n"),
      suggestedTimelineLabel: "Legal caveat",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.legalNote,
      issueRecordImpacts: {
        claimsAdded: [NORTHBANK_CLAIM_IDS.c5],
        gapsOpened: [NORTHBANK_GAP_IDS.greenProposition],
        observationsAdded: [NORTHBANK_OBSERVATION_IDS.o1],
      },
    },
    { eventOccurredAt: "2026-06-10T14:30:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.customerOps,
      inputType: "CUSTOMER OPS",
      title: "Customer operations requests approved agent line",
      senderTeam: "Customer Operations",
      channel: "ops request",
      summary: "Contact centre asks for a simple approved line for agents before launch announcement.",
      fullText: [
        "Customer operations — agent script request",
        "",
        "Contact centre needs a short approved line for inbound calls once announcement is authorised.",
        "Agents must not speculate on rate, eligibility or launch date until message variants are approved in Metis.",
        "Escalation path to product specialist team to be referenced in internal staff variant.",
      ].join("\n"),
      suggestedTimelineLabel: "Agent line needed",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.customerOps,
      issueRecordImpacts: {
        claimsAdded: [NORTHBANK_CLAIM_IDS.c6],
        gapsOpened: [NORTHBANK_GAP_IDS.customerOpsLine],
        observationsAdded: [NORTHBANK_OBSERVATION_IDS.o4],
      },
    },
    { eventOccurredAt: "2026-06-11T10:00:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.accessibilityReview,
      inputType: "ACCESSIBILITY REVIEW",
      title: "Accessibility review asks for alternative support wording",
      senderTeam: "Accessibility and Inclusion",
      channel: "accessibility review",
      summary: "Accessibility team asks for clearer wording for customers who cannot use the app or need assisted digital support.",
      fullText: [
        "Accessibility and inclusion review",
        "",
        "Customer-facing materials must include assisted digital and non-digital support routes.",
        "Do not present app-only journeys as the only way to apply or manage the product.",
        "Vulnerable customer considerations to be reflected in internal staff and customer variants.",
      ].join("\n"),
      suggestedTimelineLabel: "Accessibility wording",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.accessibilityReview,
      issueRecordImpacts: {
        claimsAdded: [NORTHBANK_CLAIM_IDS.c7],
        gapsOpened: [NORTHBANK_GAP_IDS.assistedDigital],
      },
    },
    { eventOccurredAt: "2026-06-12T09:30:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.digitalReadiness,
      inputType: "DIGITAL READINESS",
      title: "App release dependency still open",
      senderTeam: "Digital Product",
      channel: "release status",
      summary: "App release is on track but final build approval is not complete.",
      fullText: [
        "Digital readiness — mobile app release",
        "",
        "Green Saver journey build on track for target launch window.",
        "Final app store / release approval not yet granted.",
        "Comms must not state that customers can apply via the app until release approval is recorded.",
      ].join("\n"),
      suggestedTimelineLabel: "App dependency open",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.digitalReadiness,
      issueRecordImpacts: {
        claimsAdded: [NORTHBANK_CLAIM_IDS.c8],
        gapsOpened: [NORTHBANK_GAP_IDS.appRelease],
        observationsAdded: [NORTHBANK_OBSERVATION_IDS.o6],
      },
    },
    { eventOccurredAt: "2026-06-15T09:00:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.execRequest,
      inputType: "EXEC REQUEST",
      title: "Executive office requests launch readiness brief",
      senderTeam: "Executive Office",
      channel: "email to Corporate Affairs",
      summary: "Executive office asks Corporate Affairs for a concise readiness note before the leadership meeting.",
      fullText: [
        "Executive office request",
        "",
        "Please provide a concise launch readiness brief for the leadership meeting covering:",
        "- confirmed position and dependencies",
        "- open risks and caveats",
        "- media and customer handling posture",
        "- decision points before announcement",
        "",
        "Length: maximum two pages. Audience: executive committee.",
      ].join("\n"),
      suggestedTimelineLabel: "Executive request",
      becomesSource: false,
      linkedSourceId: null,
      issueRecordImpacts: {},
    },
    { eventOccurredAt: "2026-06-15T11:15:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.partnerUpdate,
      inputType: "PARTNER UPDATE",
      title: "Green home partner content confirmed",
      senderTeam: "Partnerships",
      channel: "partner sign-off",
      summary: "Partner-facing signposting copy is confirmed, but must not imply endorsement of individual suppliers.",
      fullText: [
        "Partnerships — green home signposting",
        "",
        "Partner signposting copy approved for use on approved channels.",
        "Must not imply endorsement of individual installers or suppliers.",
        "Comms to use approved partner wording only — no extension of environmental claims.",
      ].join("\n"),
      suggestedTimelineLabel: "Partner copy",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.partnerUpdate,
      issueRecordImpacts: {},
    },
    { eventOccurredAt: "2026-06-16T10:00:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.mediaEnquiry,
      inputType: "MEDIA ENQUIRY",
      title: "Trade journalist asks about upcoming savings launch",
      senderTeam: "Press Office",
      channel: "media enquiry log",
      summary: "Trade journalist asks whether Northbank is launching a new green savings product.",
      fullText: [
        "Media enquiry — trade press (fictional)",
        "",
        "Journalist asks whether Northbank Building Society plans a new 'green' savings product.",
        "Questions: timing, rate, eligibility, environmental positioning.",
        "Deadline: response requested by 16:00 today for tomorrow's newsletter slot.",
        "No announcement authorised until go/no-go — holding line required.",
      ].join("\n"),
      suggestedTimelineLabel: "Trade press enquiry",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.mediaEnquiry,
      issueRecordImpacts: {
        observationsAdded: [NORTHBANK_OBSERVATION_IDS.o5],
      },
    },
    { eventOccurredAt: "2026-06-17T09:30:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.digitalApproval,
      inputType: "DIGITAL APPROVAL",
      title: "App release approved for launch",
      senderTeam: "Digital Product",
      channel: "release approval",
      summary: "Final app release approval confirmed. Launch dependency closed.",
      fullText: [
        "Digital approval — app release",
        "",
        "Final build approved for release in line with launch window.",
        "Customers may be directed to the app journey once customer-facing messages are approved.",
      ].join("\n"),
      suggestedTimelineLabel: "App approved",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.digitalApproval,
      issueRecordImpacts: {
        gapsClosed: [NORTHBANK_GAP_IDS.appRelease],
      },
    },
    { eventOccurredAt: "2026-06-18T10:30:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.pricingApproval,
      inputType: "PRICING APPROVAL",
      title: "Pricing committee confirms launch rate",
      senderTeam: "Commercial Pricing",
      channel: "committee minute",
      summary: "Final launch rate and eligibility wording approved.",
      fullText: [
        "Pricing committee minute extract (fictional)",
        "",
        "Launch rate 4.25% gross/AER approved for eligible customers within published limits.",
        "Eligibility wording approved for external use as per compliance pack v3.",
        "Effective from launch date subject to go/no-go.",
      ].join("\n"),
      suggestedTimelineLabel: "Pricing approved",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.pricingApproval,
      issueRecordImpacts: {
        claimsAdded: [NORTHBANK_CLAIM_IDS.c9],
        gapsClosed: [NORTHBANK_GAP_IDS.pricingApproved, NORTHBANK_GAP_IDS.eligibilityWording],
      },
    },
    { eventOccurredAt: "2026-06-18T11:45:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.goNoGo,
      inputType: "GO NO-GO",
      title: "Launch approved for announcement",
      senderTeam: "Launch Steering Group",
      channel: "go/no-go record",
      summary: "Go/no-go confirms launch can proceed, subject to final circulation of approved brief and message variants.",
      fullText: [
        "Launch steering group — go/no-go",
        "",
        "Decision: proceed to announcement in line with approved launch window.",
        "Conditions: Executive Brief V2, customer and stakeholder message variants, and press holding line circulated via Metis audit trail.",
        "Post-launch monitoring for media, customer confusion, vulnerable customers and digital journey.",
      ].join("\n"),
      suggestedTimelineLabel: "Go for launch",
      becomesSource: true,
      linkedSourceId: NORTHBANK_SOURCE_IDS.goNoGo,
      issueRecordImpacts: {
        claimsAdded: [NORTHBANK_CLAIM_IDS.c10],
        gapsClosed: [NORTHBANK_GAP_IDS.customerOpsLine],
        statusNote: "Launch approved for announcement",
      },
    },
    { eventOccurredAt: "2026-06-19T09:00:00" },
  ),
  directToComms(
    {
      id: NORTHBANK_INPUT_IDS.execAction,
      inputType: "EXEC ACTION",
      title: "Post-launch watchlist requested",
      senderTeam: "Corporate Affairs Director",
      channel: "director note",
      summary:
        "Director asks for a short watchlist covering media, customer confusion, vulnerable customers and digital journey issues for the first 72 hours after announcement.",
      fullText: [
        "Corporate Affairs Director — post-launch watchlist",
        "",
        "Please maintain a short leadership watchlist for the first 72 hours covering:",
        "- trade and consumer media pickup",
        "- customer confusion on eligibility or environmental claims",
        "- vulnerable customer and assisted digital contacts",
        "- digital journey defects or complaints",
        "",
        "Update Metis issue record as items are confirmed or closed.",
      ].join("\n"),
      suggestedTimelineLabel: "Watchlist requested",
      becomesSource: false,
      linkedSourceId: null,
      issueRecordImpacts: {
        gapsOpened: [NORTHBANK_GAP_IDS.postLaunchWatch],
        observationsAdded: [NORTHBANK_OBSERVATION_IDS.o3],
      },
    },
    { eventOccurredAt: "2026-06-19T10:15:00" },
  ),
];
