import {
  NORTHBANK_CLAIM_IDS,
  NORTHBANK_GAP_IDS,
  NORTHBANK_INPUT_IDS,
  NORTHBANK_OBSERVATION_IDS,
  NORTHBANK_SOURCE_IDS,
} from "./ids";
import type {
  NorthbankClaimExport,
  NorthbankObservationExport,
  NorthbankOpenQuestionExport,
  NorthbankSourceExport,
} from "./types";
import { northbankIncomingUpdates } from "./incoming-inputs";
import { northbankIso } from "./timestamps";

function inputById(id: string) {
  const row = northbankIncomingUpdates.find((u) => u.id === id);
  if (!row) throw new Error(`Missing Northbank input ${id}`);
  return row;
}

function metisAddedAt(inputId: string): string {
  return inputById(inputId).addedToMetisAt;
}

const northbankSourcesBase = [
  {
    id: NORTHBANK_SOURCE_IDS.productScope,
    sourceCode: "SRC-001",
    title: "Product launch scope — Green Saver",
    tier: "Product source",
    reliability: "High (product team launch pack)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.productScope}`,
    snippet: "Target launch window week commencing 22 June; eligible savings customers; green home improvements proposition.",
    timestampLabel: "Mon 8 Jun 09:30",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.productScope,
  },
  {
    id: NORTHBANK_SOURCE_IDS.pricingUpdate,
    sourceCode: "SRC-002",
    title: "Pricing recommendation — proposed rate",
    tier: "Pricing source",
    reliability: "Medium (pending committee)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.pricingUpdate}`,
    snippet: "Proposed 4.25% gross/AER; committee approval required before external use.",
    timestampLabel: "Tue 9 Jun 10:15",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.pricingUpdate,
  },
  {
    id: NORTHBANK_SOURCE_IDS.complianceNote,
    sourceCode: "SRC-003",
    title: "Compliance review — eligibility wording",
    tier: "Compliance source",
    reliability: "High (compliance review)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.complianceNote}`,
    snippet: "Not available to all customers; eligibility wording required before external use.",
    timestampLabel: "Wed 10 Jun 09:45",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.complianceNote,
  },
  {
    id: NORTHBANK_SOURCE_IDS.legalNote,
    sourceCode: "SRC-004",
    title: "Legal sign-off — environmental claims caveat",
    tier: "Legal source",
    reliability: "High (legal sign-off)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.legalNote}`,
    snippet: "Broad narrative approved; avoid overclaiming on environmental outcomes.",
    timestampLabel: "Wed 10 Jun 14:30",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.legalNote,
  },
  {
    id: NORTHBANK_SOURCE_IDS.customerOps,
    sourceCode: "SRC-005",
    title: "Customer operations — agent line request",
    tier: "Customer operations source",
    reliability: "High (operations request)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.customerOps}`,
    snippet: "Contact centre requires approved agent line before announcement.",
    timestampLabel: "Thu 11 Jun 10:00",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.customerOps,
  },
  {
    id: NORTHBANK_SOURCE_IDS.accessibilityReview,
    sourceCode: "SRC-006",
    title: "Accessibility review — assisted digital wording",
    tier: "Accessibility source",
    reliability: "High (accessibility review)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.accessibilityReview}`,
    snippet: "Include assisted digital and non-digital support routes in customer materials.",
    timestampLabel: "Fri 12 Jun 09:30",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.accessibilityReview,
  },
  {
    id: NORTHBANK_SOURCE_IDS.digitalReadiness,
    sourceCode: "SRC-007",
    title: "Digital readiness — app release pending",
    tier: "Digital readiness source",
    reliability: "High (digital status)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.digitalReadiness}`,
    snippet: "Build on track; final release approval not yet granted.",
    timestampLabel: "Mon 15 Jun 09:00",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.digitalReadiness,
  },
  {
    id: NORTHBANK_SOURCE_IDS.partnerUpdate,
    sourceCode: "SRC-008",
    title: "Partnerships — green home signposting copy",
    tier: "Product source",
    reliability: "High (partnerships sign-off)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.partnerUpdate}`,
    snippet: "Partner signposting approved; no supplier endorsement implied.",
    timestampLabel: "Tue 16 Jun 10:00",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.partnerUpdate,
  },
  {
    id: NORTHBANK_SOURCE_IDS.mediaEnquiry,
    sourceCode: "SRC-009",
    title: "Media enquiry — trade journalist",
    tier: "Media enquiry",
    reliability: "High (press office log)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.mediaEnquiry}`,
    snippet: "Trade journalist asks about green savings launch; holding line required.",
    timestampLabel: "Wed 17 Jun 09:30",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.mediaEnquiry,
  },
  {
    id: NORTHBANK_SOURCE_IDS.digitalApproval,
    sourceCode: "SRC-010",
    title: "Digital approval — app release",
    tier: "Digital readiness source",
    reliability: "High (release approval)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.digitalApproval}`,
    snippet: "Final app build approved for launch window.",
    timestampLabel: "Thu 18 Jun 10:30",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.digitalApproval,
  },
  {
    id: NORTHBANK_SOURCE_IDS.pricingApproval,
    sourceCode: "SRC-011",
    title: "Pricing committee — launch rate approved",
    tier: "Pricing source",
    reliability: "High (committee minute)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.pricingApproval}`,
    snippet: "4.25% gross/AER and eligibility wording approved for external use.",
    timestampLabel: "Thu 18 Jun 11:45",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.pricingApproval,
  },
  {
    id: NORTHBANK_SOURCE_IDS.goNoGo,
    sourceCode: "SRC-012",
    title: "Launch steering group — go/no-go",
    tier: "Decision record",
    reliability: "High (steering group record)",
    note: `Linked incoming update ${NORTHBANK_INPUT_IDS.goNoGo}`,
    snippet: "Proceed to announcement subject to circulated approved outputs.",
    timestampLabel: "Fri 19 Jun 09:00",
    linkedIncomingUpdateId: NORTHBANK_INPUT_IDS.goNoGo,
  },
] as const;

export const northbankSources: NorthbankSourceExport[] = northbankSourcesBase.map((s) => {
  const input = inputById(s.linkedIncomingUpdateId);
  return { ...s, eventOccurredAt: input.eventOccurredAt, addedToMetisAt: input.addedToMetisAt };
});

export const northbankClaims: NorthbankClaimExport[] = [
  {
    id: NORTHBANK_CLAIM_IDS.c1,
    claimCode: "CLM-001",
    text: "Green Saver is planned for launch in the stated launch window (week commencing 22 June 2026, subject to dependencies).",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.productScope],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.productScope],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.productScope),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.productScope),
  },
  {
    id: NORTHBANK_CLAIM_IDS.c2,
    claimCode: "CLM-002",
    text: "The product is intended for eligible savings customers meeting published criteria.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.productScope, NORTHBANK_SOURCE_IDS.complianceNote],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.productScope, NORTHBANK_INPUT_IDS.complianceNote],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.productScope),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.complianceNote),
  },
  {
    id: NORTHBANK_CLAIM_IDS.c3,
    claimCode: "CLM-003",
    text: "A launch rate of 4.25% gross/AER was proposed pending pricing committee approval.",
    status: "NeedsValidation",
    notes: "Superseded by committee-approved rate once SRC-011 is in Metis.",
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.pricingUpdate],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.pricingUpdate],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingUpdate),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingApproval),
  },
  {
    id: NORTHBANK_CLAIM_IDS.c4,
    claimCode: "CLM-004",
    text: "Eligibility wording requires compliance approval before external customer or media use.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.complianceNote],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.complianceNote],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.complianceNote),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingApproval),
  },
  {
    id: NORTHBANK_CLAIM_IDS.c5,
    claimCode: "CLM-005",
    text: "Environmental wording must avoid overclaiming and must not imply guaranteed green outcomes.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.legalNote],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.legalNote],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.legalNote),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.legalNote),
  },
  {
    id: NORTHBANK_CLAIM_IDS.c6,
    claimCode: "CLM-006",
    text: "Customer operations require an approved agent line before public announcement.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.customerOps],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.customerOps],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.customerOps),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.goNoGo),
  },
  {
    id: NORTHBANK_CLAIM_IDS.c7,
    claimCode: "CLM-007",
    text: "Assisted digital and vulnerable customer support wording must be included in launch materials.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.accessibilityReview],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.accessibilityReview],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.accessibilityReview),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.accessibilityReview),
  },
  {
    id: NORTHBANK_CLAIM_IDS.c8,
    claimCode: "CLM-008",
    text: "Mobile app release approval is a launch dependency until formally recorded.",
    status: "Confirmed",
    notes: "Closed when digital approval recorded.",
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.digitalReadiness, NORTHBANK_SOURCE_IDS.digitalApproval],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.digitalReadiness, NORTHBANK_INPUT_IDS.digitalApproval],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.digitalReadiness),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.digitalApproval),
  },
  {
    id: NORTHBANK_CLAIM_IDS.c9,
    claimCode: "CLM-009",
    text: "Pricing committee approved the launch rate (4.25% gross/AER) and eligibility wording for external use.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.pricingApproval],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.pricingApproval],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingApproval),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingApproval),
  },
  {
    id: NORTHBANK_CLAIM_IDS.c10,
    claimCode: "CLM-010",
    text: "Launch steering group approved proceeding to announcement subject to circulated approved outputs.",
    status: "Confirmed",
    notes: null,
    linkedSourceIds: [NORTHBANK_SOURCE_IDS.goNoGo],
    linkedIncomingUpdateIds: [NORTHBANK_INPUT_IDS.goNoGo],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.goNoGo),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.goNoGo),
  },
];

export const northbankOpenQuestions: NorthbankOpenQuestionExport[] = [
  {
    id: NORTHBANK_GAP_IDS.pricingApproved,
    gapCode: "Q-001",
    title: "Has pricing been formally approved?",
    prompt: "Can we quote the launch rate externally?",
    whyItMatters: "Quoting an unapproved rate creates regulatory and conduct risk.",
    stakeholder: "Commercial Pricing / Compliance",
    severity: "Critical",
    status: "Resolved",
    partiallyAnsweredAt: null,
    resolvedAt: northbankIso("2026-06-18T11:45:00"),
    resolvedByIncomingUpdateId: NORTHBANK_INPUT_IDS.pricingApproval,
    resolutionNote: "Pricing committee minute recorded in Metis.",
    linkedClaimIds: [NORTHBANK_CLAIM_IDS.c3, NORTHBANK_CLAIM_IDS.c9],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingUpdate),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingApproval),
  },
  {
    id: NORTHBANK_GAP_IDS.eligibilityWording,
    gapCode: "Q-002",
    title: "What eligibility wording is approved for external use?",
    prompt: "Which eligibility text can customer and media variants use?",
    whyItMatters: "Mis-stating eligibility creates fair value and customer detriment risk.",
    stakeholder: "Compliance",
    severity: "Critical",
    status: "Resolved",
    partiallyAnsweredAt: northbankIso("2026-06-10T14:30:00"),
    resolvedAt: northbankIso("2026-06-18T11:45:00"),
    resolvedByIncomingUpdateId: NORTHBANK_INPUT_IDS.pricingApproval,
    resolutionNote: "Compliance pack v3 eligibility wording approved with pricing committee.",
    linkedClaimIds: [NORTHBANK_CLAIM_IDS.c2, NORTHBANK_CLAIM_IDS.c4],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.complianceNote),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingApproval),
  },
  {
    id: NORTHBANK_GAP_IDS.greenProposition,
    gapCode: "Q-003",
    title: "What can we safely say about the green proposition?",
    prompt: "What environmental claims are approved for external use?",
    whyItMatters: "Overclaiming on green outcomes creates legal and reputational risk.",
    stakeholder: "Legal / Corporate Affairs",
    severity: "Important",
    status: "Resolved",
    partiallyAnsweredAt: northbankIso("2026-06-10T14:30:00"),
    resolvedAt: northbankIso("2026-06-10T14:30:00"),
    resolvedByIncomingUpdateId: NORTHBANK_INPUT_IDS.legalNote,
    resolutionNote: "Legal approved support/linked-to language with anti-overclaiming caveats.",
    linkedClaimIds: [NORTHBANK_CLAIM_IDS.c5],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.complianceNote),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.legalNote),
  },
  {
    id: NORTHBANK_GAP_IDS.appRelease,
    gapCode: "Q-004",
    title: "Is the app release approved?",
    prompt: "Can we direct customers to the app journey?",
    whyItMatters: "Directing customers to an unavailable journey creates conduct risk.",
    stakeholder: "Digital Product",
    severity: "Important",
    status: "Resolved",
    partiallyAnsweredAt: null,
    resolvedAt: northbankIso("2026-06-18T10:30:00"),
    resolvedByIncomingUpdateId: NORTHBANK_INPUT_IDS.digitalApproval,
    resolutionNote: "Final build approval recorded.",
    linkedClaimIds: [NORTHBANK_CLAIM_IDS.c8],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.digitalReadiness),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.digitalApproval),
  },
  {
    id: NORTHBANK_GAP_IDS.customerOpsLine,
    gapCode: "Q-005",
    title: "What line should customer operations use before launch?",
    prompt: "What approved agent script is available?",
    whyItMatters: "Agents need a controlled line before announcement.",
    stakeholder: "Customer Operations",
    severity: "Important",
    status: "Resolved",
    partiallyAnsweredAt: northbankIso("2026-06-11T15:00:00"),
    resolvedAt: northbankIso("2026-06-19T09:00:00"),
    resolvedByIncomingUpdateId: NORTHBANK_INPUT_IDS.goNoGo,
    resolutionNote: "Internal staff message variant V1 circulated; go/no-go confirmed announcement authorised.",
    linkedClaimIds: [NORTHBANK_CLAIM_IDS.c6],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.customerOps),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.goNoGo),
  },
  {
    id: NORTHBANK_GAP_IDS.assistedDigital,
    gapCode: "Q-006",
    title: "What support wording is needed for assisted digital/vulnerable customers?",
    prompt: "Are assisted digital routes clearly stated in customer variants?",
    whyItMatters: "Vulnerable customers must not be directed to digital-only journeys.",
    stakeholder: "Accessibility and Inclusion",
    severity: "Important",
    status: "Resolved",
    partiallyAnsweredAt: northbankIso("2026-06-11T15:00:00"),
    resolvedAt: northbankIso("2026-06-18T13:00:00"),
    resolvedByIncomingUpdateId: NORTHBANK_INPUT_IDS.digitalApproval,
    resolutionNote: "Reflected in staff V1 and customer V2 variants; ongoing monitoring via watchlist.",
    linkedClaimIds: [NORTHBANK_CLAIM_IDS.c7],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.accessibilityReview),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingApproval),
  },
  {
    id: NORTHBANK_GAP_IDS.postLaunchWatch,
    gapCode: "Q-007",
    title: "What should be watched in the first 72 hours after launch?",
    prompt: "What items are on the post-launch watchlist?",
    whyItMatters: "Leadership expects disciplined monitoring after announcement.",
    stakeholder: "Corporate Affairs",
    severity: "Watch",
    status: "Open",
    partiallyAnsweredAt: null,
    resolvedAt: null,
    resolvedByIncomingUpdateId: null,
    resolutionNote: "Watchlist brief issued; items to be updated as confirmed during 72-hour window.",
    linkedClaimIds: [],
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.execAction),
    updatedAt: metisAddedAt(NORTHBANK_INPUT_IDS.execAction),
  },
];

export const northbankObservations: NorthbankObservationExport[] = [
  {
    id: NORTHBANK_OBSERVATION_IDS.o1,
    observationCode: "OBS-001",
    title: "Overclaiming risk before approvals",
    body: "The main comms risk is stating rate, eligibility or app availability before formal approvals are in Metis.",
    confidence: "Confirmed",
    authorRole: "Corporate Affairs",
    authorName: "Launch Readiness Lead",
    timestampLabel: "Wed 10 Jun",
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.pricingUpdate),
  },
  {
    id: NORTHBANK_OBSERVATION_IDS.o2,
    observationCode: "OBS-002",
    title: "Positive product story needs caveats",
    body: "The product story is positive but requires disciplined caveats — this is readiness, not a campaign.",
    confidence: "Likely",
    authorRole: "Corporate Affairs",
    authorName: "Launch Readiness Lead",
    timestampLabel: "Mon 8 Jun",
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.productScope),
  },
  {
    id: NORTHBANK_OBSERVATION_IDS.o3,
    observationCode: "OBS-003",
    title: "Leadership needs readiness not a campaign plan",
    body: "Executive audience needs a readiness view with dependencies and decisions — not marketing campaign detail.",
    confidence: "Confirmed",
    authorRole: "Corporate Affairs",
    authorName: "Launch Readiness Lead",
    timestampLabel: "Mon 8 Jun",
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.commsIntake),
  },
  {
    id: NORTHBANK_OBSERVATION_IDS.o4,
    observationCode: "OBS-004",
    title: "Ops and accessibility are launch dependencies",
    body: "Customer operations and accessibility wording should be treated as launch readiness dependencies, not afterthoughts.",
    confidence: "Likely",
    authorRole: "Corporate Affairs",
    authorName: "Launch Readiness Lead",
    timestampLabel: "Thu 11 Jun",
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.customerOps),
  },
  {
    id: NORTHBANK_OBSERVATION_IDS.o5,
    observationCode: "OBS-005",
    title: "Trade press may force holding line",
    body: "Trade press interest may require a holding line before final go/no-go even when internal confidence is high.",
    confidence: "Likely",
    authorRole: "Press Office",
    authorName: "Press Manager",
    timestampLabel: "Wed 17 Jun",
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.mediaEnquiry),
  },
  {
    id: NORTHBANK_OBSERVATION_IDS.o6,
    observationCode: "OBS-006",
    title: "Version compare should show approval changes",
    body: "Executive brief comparison should highlight what changed after digital and pricing approvals.",
    confidence: "Likely",
    authorRole: "Corporate Affairs",
    authorName: "Launch Readiness Lead",
    timestampLabel: "Mon 15 Jun",
    createdAt: metisAddedAt(NORTHBANK_INPUT_IDS.digitalReadiness),
  },
];
